[package]
name = "alicesaidhi/videkit-ty"
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["src/stories"]

[dependencies]
vide = "aloroid/vide-with-types@0.2.3"